name: Setup ruby
on: push

jobs:
  build-ios:
    name: Setup ruby
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7.2
          bundler-cache: true
      - run: bundle exec fastlane ios custom_lane
